[workspace]
resolver = "2"
members = ["interface", "program"]

[workspace.metadata.cli]
solana = "3.0.0"

# Specify Rust toolchains for rustfmt, clippy, and build.
# Any unprovided toolchains default to stable.
[workspace.metadata.toolchains]
format = "nightly-2025-02-16"
lint = "nightly-2025-02-16"

[workspace.metadata.spellcheck]
config = "scripts/spellcheck.toml"

# Unfortunately we still need a lot of patches in order for Mollusk to work
[patch.crates-io]
solana-address = { version = "1.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-pubkey = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-sdk = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-program-entrypoint = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-program-error = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-program-runtime = { version = "3.0", git = "https://github.com/anza-xyz/agave.git" }
solana-sysvar = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-sysvar-id = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-account = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-account-info = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-instruction = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-message = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-instruction-error = { version = "2.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-transaction-context = { version = "3.0", git = "https://github.com/anza-xyz/agave.git" }
solana-transaction-error = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-signer = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-nonce = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-bincode = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-transaction     = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-sanitize        = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-hash            = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-nonce-account   = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-signature = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-rent = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-slot-hashes = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-slot-history = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-epoch-schedule = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-epoch-rewards = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-clock = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-last-restart-slot = { version = "3.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-compute-budget = { version = "3.0", git = "https://github.com/anza-xyz/agave.git" }
solana-svm-timings = { version = "3.0", git = "https://github.com/anza-xyz/agave.git" }
solana-svm-callback = { version = "3.0", git = "https://github.com/anza-xyz/agave.git" }
solana-bpf-loader-program = { version = "3.0", git = "https://github.com/anza-xyz/agave.git" }
solana-loader-v3-interface = { version = "6.1.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-loader-v4-interface = { version = "3.1.0", git = "https://github.com/anza-xyz/solana-sdk.git" }
solana-stake-program = { version = "3.1", git = "https://github.com/anza-xyz/agave.git" }
spl-associated-token-account = { version = "7.0.0", git = "https://github.com/solana-program/associated-token-account.git" }