[workspace]

[package]
name = "pinocchio-ata-program"
version = "0.1.0"
description = "A pinocchio-based Associated Token Account (aka 'p-ata') program"
readme = "./README.md"
autobenches = false
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

# Build script (build.rs) compiles token programs during benchmarks

[features]
create-account-prefunded = []
build-programs = []
comparison-bench = ["build-programs"]
default = []
full-debug-logs = []
bench-transfer-unchecked = []
test-debug = []

[build-dependencies]
serde_json = "1.0"
solana-pubkey = "2.2.1"

[patch.crates-io]
pinocchio = { version = "0.8.4", git = "https://github.com/rustopian/pinocchio.git", branch = "create-account-prefunded", default-features = false }
pinocchio-system = { version = "0.2.3", git = "https://github.com/rustopian/pinocchio.git", branch = "create-account-prefunded" }
indicatif = { git = "https://github.com/mitsuhiko/indicatif", tag = "0.18.0" }

[dependencies]
pinocchio = { version = "0.8.4", git = "https://github.com/rustopian/pinocchio.git", branch = "create-account-prefunded", default-features = false }
pinocchio-log = { version = "0.4", default-features = false }
pinocchio-pubkey = { verison = "0.2.4", git = "https://github.com/anza-xyz/pinocchio.git" }
pinocchio-system = { version = "0.2.3", git = "https://github.com/rustopian/pinocchio.git", branch = "create-account-prefunded" }
pinocchio-token = "0.3.0"
solana-program-option = "2.2.1"
spl-token-interface = { version = "^0", git = "https://github.com/solana-program/token.git" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
curve25519-dalek = { version = "4.2.0", default-features = false }
assert_matches = "1.5.0"
num-traits = "0.2"
solana-account = "2.2.1"
solana-instruction = "2.3.0"
solana-keypair = "2.2.3"
solana-logger = "2.3.0"
solana-pubkey = { version = "2.2.1", features = ["curve25519"] }
solana-sdk-ids = "2.2.1"
solana-signature = "2.3.0"
solana-signer = "2.2.1"
solana-sysvar = "2.2.2"
solana-system-interface = "1.0.0"
solana-program-test = { version = "2.3.4" }
solana-seed-derivable = "2.2.1"
spl-token = { version="^4", features=["no-entrypoint"] }
spl-token-2022 = { version="^7", features=["no-entrypoint"] }
mollusk-svm = { version = "0.3.0", git = "https://github.com/rustopian/mollusk.git", branch = "v3.0", features = ["all-builtins"] }
mollusk-svm-bencher = { version = "0.3.0", git = "https://github.com/rustopian/mollusk.git", branch = "v3.0" }
serde_json = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
comfy-table = "7"
strum = { version = "0.27.1", features = ["derive"] }
test-case = "3.3.1"
bs58 = "0.4.0"
colored = "2.0"
itertools = "0.12"
solana-program = "2.3.0"
solana-sdk = "2.3.1"
spl-associated-token-account = "7.0.0"
spl-associated-token-account-client = "2.0.0"
bincode = "1.3.3"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread", "sync"] }
spl-token-metadata-interface = "0.6"
spl-token-group-interface = "0.6.0"

[[bench]]
name = "ata_instruction_benches"
harness = false

[[bench]]
name = "failure_scenarios"
harness = false

