[package]
name = "spl-associated-token-account"
version = "7.0.0"
description = "Solana Program Library Associated Token Account"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/solana-program/associated-token-account"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
borsh = "1.5.7"
num-derive = "0.4"
num-traits = "0.2"
solana-decode-error = "2.3.0"
solana-program = "3.0"
solana-pubkey = "3.0"
solana-system-interface = { version = "2.0", features = ["bincode"] }
spl-associated-token-account-interface = { version = "2.0.0", features = ["borsh"] }
spl-token-interface = "2.0.0"
spl-token-2022-interface = "2.0.0"
thiserror = "2.0"

[dev-dependencies]
solana-program-test = "3.0"
solana-sdk = "3.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
